# NumPy
---
In this tutorial, we are going to learn about NumPy and how to use it.

NumPy, or simply Numpy, is a Python's linear algebra library that allows working with large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

One of the most important PyData libraries (used for Data Science), Numpy is used as the base for almost all other PyData libraries, hence is very important that you understand how to work with NumPy.

One of the advantages that Numpy has over Python's built-in lists is its bindings with the C-programming language, which allows mathematical functions to be performed at much faster speeds as compared to on the built-in lists. 

Now that we have the basic idea regarding what Numpy is, let us start working with it.

## Importing NumPy
---
Before any project in which you want to use Numpy, add the following line of code to import Numpy.

In [1]:
import numpy as np # importing numpy as np means in order to use numpy, you can simply type np 

In this tutorial, we will focus on some of the most important fundamental data types of Numpy— vectors, arrays, matrices, and we alsp be working on various number generation methods. 

## NumPy Arrays
---

Numpy arrays are the fundamental data type of Numpy, and is the primary way how Numpy works with data. The array object in NumPy is called ndarray.

Numpy arrays essentially come in two flavors: 
* Vectors, and 
* Matrices 

Vectors are 1-d arrays. On the other hand, matrices are 2-d arrays of the dimension __m x n__ where m, n >= 1. This means that a matrix can still have only one row or one column.

Let's have a look at the different ways that you can create a Numpy array with.

### A. How to Create NumPy Arrays
---

__1. Numpy Arrays from a Python List:__

We can create a numpy array by directly converting a list or list of lists. For this, we use the array() method. 

The following is the syntax:
> numpy_arr = np.array(python_list)

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray object.

In [2]:
# creating a 1D python list
arr = [1, 2, 3, 4, 5, 6]
arr

[1, 2, 3, 4, 5, 6]

In [3]:
# creating a numpy array from the python list
np.array(arr)

array([1, 2, 3, 4, 5, 6])

In [4]:
# creating a 2D python list
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
# creating a numpy array from the python list
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### B. Built-in Methods:
---
Here, we will se a bunch of built-in Numpy methods for a bunch of different array operation.

#### (a). arange
This method returns evenly spaced values within a given range. The following is the syntax:
> np.arange(start, stop, step), where, 
* start -> Starting value 
* stop -> Right upper bound of the range 
* step -> The size of the step; number of values to skip

In [6]:
# an array with all values in range 0-10 (excluding 10)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# an array with values in range 0-10 (excluding 10) and a step size of 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

#### (b). zeros

The zeros() method returns an array of zeros. The following is the syntax-  
> np.zeros(shape), where,
* shape -> Shape of the array; tuple

In [8]:
# array of 0s
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# matrix of 0s
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### (c). ones
The ones() method returns an array of ones. The following is the syntax-  
> np.ones(shape), where,
* shape -> Shape of the array; tuple

In [10]:
# vector of 1s
np.ones((5))

array([1., 1., 1., 1., 1.])

In [11]:
# matrix of 1s
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### (d). linspace
This method returns evenly spaced numbers over a specific interval. The following is the syntax-
> np.linspace(start, stop, num = 50), where,
* start -> Starting value
* stop -> Stopping value
* num -> Number of evenly-spaced values between the start and stop index. 

In [12]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [13]:
np.linspace(0, 100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

#### (e). eye

This method returns an identity matrix (i.e., a unique matrix that has 0 for all elements except the diagonal elements). The following is the syntax-
> np.eye(shape), where,
* shape -> Shape of the matrix


In [14]:
# creating a square identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# creating an arbitrary identity matrix
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

### C. NumPy Random Methods
---

Numpy's random methods allow us to randomly generate and work with random integers and floating point number. In this section, we will cover some of the most important random methods.

#### (a). rand

The rand() method returns an array of the given shape and populates it with random samples from a ***uniform distribution***
over the range ``[0, 1)``. The following is the syntax-
> np.random.rand(b<sub>0</sub>, b<sub>1</sub>, b<sub>2</sub>....), where,
* b<sub>n</sub> -> Size of n<sup>th</sup> dimension 


In [16]:
# vector with random values between [0,1)
np.random.rand(5)

array([0.06399243, 0.85547936, 0.79928   , 0.33821026, 0.67997203])

In [17]:
# matrix with random values between [0,1)
np.random.rand(3, 2)

array([[0.39069786, 0.14865308],
       [0.92114211, 0.27995269],
       [0.35875422, 0.8048765 ]])

#### (b). randn
The randn() method, just like rand() also returns an array with randomly generated values. The only difference is that the value are samples from a ***standard normal distribution***. The following is the syntax-
> np.random.randn(b<sub>0</sub>, b<sub>1</sub>, b<sub>2</sub>....), where,
* b<sub>n</sub> -> Size of n<sup>th</sup> dimension 


In [18]:
# vector with random values from a standard normal distribution
np.random.randn(5)

array([-1.73560341, -1.01887197, -1.84549986, -0.2974967 , -1.4802113 ])

In [19]:
# matrix with random values from a standard normal distribution
np.random.randn(3,4)

array([[-0.24250848, -0.59005408,  0.55390538,  0.79762847],
       [-0.39089488, -0.01719783, -0.71743835,  0.04024788],
       [ 0.06033217, -0.7766337 , -0.0417169 , -0.35747097]])

#### (c). randint

The randint() method returns an array of integers in the specified range. The following is the syntax-
> np.random.randint(low, high, size), where,
* low -> Left limit of the range (inclusive)
* high -> Right limit of the range (exclusive)
* size -> Shape of the array

In [20]:
# vector of 5 random integers between 0-10 
np.random.randint(0, 10, 5)

array([1, 6, 8, 3, 5])

In [21]:
# matrix of random integers between 10-50 of the shape 3x4
np.random.randint(10, 50, (3,4))

array([[19, 35, 25, 14],
       [27, 38, 16, 44],
       [42, 20, 31, 35]])

These were one of the most useful of the Numpy random class. To check for more methods, refer [here](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html).

Now, let us have a look at some of the important array methods in Numpy.

### D. Array Attributes and methods
---

#### (a). reshape
The reshape() method is used to, as the name suggest, change the shape of the array. While the data in the array remains the same, we can cast it to a different shape using the reshape method. The following is the syntax-
> numpy_arr.reshape(shape), where, 
* shape -> New shape that you want to cast the array to; tuple

One thing to be noted is that the total number of elements in the original array and the dimensions of the new array should be the same.


In [22]:
# creating a new array
arr = np.arange(0,20)

# reshaping the array
arr.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Now, let see what happens when you enter a reshape size that does not meet the number of elements in the initial array. 

*__Hint__: We will run into an error!*

In [23]:
# Number of elements in arr = 20
# reshape size = 3,4 -> 3 * 4 = 12
arr.reshape(3,4)

ValueError: cannot reshape array of size 20 into shape (3,4)

#### (b). max & min

As the name suggests, the max() method returns the largest element in the array. The syntax is-
> arr.max()

The min() method returns the smallest element in the array. The syntax is-
> arr.min()

In [24]:
# getting the largest element
arr = np.array([1,5,2,4,8,3])
arr.max()

8

In [25]:
# getting the smallest element
arr = np.array([1,5,2,4,8,3])
arr.min()

1

#### (c). argmax & argmin

The argmax() method returns the index of the largest element in the array. The syntax is-
> arr.argmax()

The argmin() method returns the index of the largest element in the array. The syntax is-
> arr.argmin()


In [26]:
arr = np.array([6,3,1,9,6,4,5,2,3,9])
# getting the index of the largest element in the array
arr.argmax()

3

In [27]:
# getting the index of the smallest element in the array
arr.argmin()

2

#### (d). shape
The shape attribute \[not a method] returns the shape of the array.

In [28]:
# shape of a vector
arr = np.array([5,3,1,7,2,4,3,5,9])
arr.shape

(9,)

In [29]:
# shape of a matrix
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.shape

(3, 3)

#### (e). dtype

The dtype attribute returns the data type of the elements in the array.

In [30]:
arr = np.array(['a', 'b', 'c', 'd'])
arr.dtype

dtype('<U1')

In [31]:
arr2 = np.array([1.3, 4.5, 1.7])
arr2.dtype

dtype('float64')

In [32]:
arr3 = np.array([1, 2, 3, 4, 5])
arr3.dtype

dtype('int64')

### C. NumPy Indexing Operations
---
Now that we know how to create an array, in this section, we will have a look at the different indexing, slicing and selection operations in Numpy. 

#### (a). Bracket Indexing and Selection

Just like Python lists, you can use bracket selection and indexing to select one or more than one elements from a numpy array.

In [33]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
# selecting element at a certain index
arr[5]

15

In [35]:
# selecting a range of elements
arr[1:6]

array([11, 12, 13, 14, 15])

In [36]:
# selecting a range of elements
arr[:8]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [37]:
arr2 = np.random.rand(4, 5)
arr2

array([[0.64929634, 0.88757019, 0.72099746, 0.92824813, 0.06852395],
       [0.82790835, 0.61992257, 0.87663491, 0.17981447, 0.62324275],
       [0.22318656, 0.34921396, 0.97579773, 0.61951198, 0.840482  ],
       [0.05077044, 0.39665052, 0.07131009, 0.4904567 , 0.29626973]])

In [38]:
# selecting a 2d slice
arr2[1:3, 2:4]

array([[0.87663491, 0.17981447],
       [0.97579773, 0.61951198]])

In [39]:
# selecting a all rows but restricting columns
arr2[:, 2:4]

array([[0.72099746, 0.92824813],
       [0.87663491, 0.17981447],
       [0.97579773, 0.61951198],
       [0.07131009, 0.4904567 ]])

#### (b). Broadcasting
Broadcasting is a unique property of Numpy arrays that sets it apart from how we can use Python lists. 

In [40]:
arr = np.random.randint(20, 100, (6,7))
arr

array([[88, 71, 68, 98, 78, 68, 32],
       [20, 35, 27, 47, 52, 39, 96],
       [89, 52, 88, 59, 84, 24, 75],
       [65, 40, 38, 80, 78, 78, 89],
       [22, 56, 44, 36, 83, 50, 32],
       [72, 49, 55, 93, 71, 50, 72]])

In [41]:
# broadcasting a slice
arr[:3, :4] = 0
arr

array([[ 0,  0,  0,  0, 78, 68, 32],
       [ 0,  0,  0,  0, 52, 39, 96],
       [ 0,  0,  0,  0, 84, 24, 75],
       [65, 40, 38, 80, 78, 78, 89],
       [22, 56, 44, 36, 83, 50, 32],
       [72, 49, 55, 93, 71, 50, 72]])

**__NOTE__: If you broadcast an array or a slice of an array as another variable, this new variable will not be a different array but actually act as an alias for the original array (or the slice of the original array). This new array will actually be referencing to the old array's location in the storage.*

*What this means is that any change in the new array will reflect in old array as well. This is known as the concept of referencing and the idea behind this is to save storage space.*

In [42]:
# original array
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
# referenced array generated from broadcasting
ref_arr = arr[2:4]
ref_arr 

array([12, 13])

In [44]:
# broadcasting all values of ref_arr as 0
ref_arr[:] = 0
ref_arr

array([0, 0])

In [45]:
# checking if the values changed in arr as well
arr

array([10, 11,  0,  0, 14, 15, 16, 17, 18, 19])

As we can see, the values changed in the old array too. Now, here's how you get a dereferenced copy of a Numpy array.

#### (c). copy

The copy method allows you create a dereferenced copy of a Numpy array. The syntax is as follows-
> new_arr = arr.copy()

In [46]:
# original array
arr = np.arange(40, 50)

# dereferenced copy of slice of old array
new_arr = arr.copy()

# broadcasting values of new_arr
new_arr[:] = 0

# checking if that changed old arr
arr

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

As expected, no change to the old array.

#### (d). Fancy Indexing
Fancy indexing can be a bit confusing as it is not quite "Pythonic". Fancy indexing is used to select entire rows of a matrix.

In [47]:
arr = np.random.randint(0, 100, (5,6))
arr

array([[61, 68, 50, 33, 44, 28],
       [98, 21,  3, 53, 72, 57],
       [23, 96, 57, 47, 97, 52],
       [81, 44, 83, 59, 28, 44],
       [10, 93,  5, 99, 20, 15]])

In [48]:
# fancy indexing row 1
arr[[1]]

array([[98, 21,  3, 53, 72, 57]])

In [49]:
# fancy indexing row 2,3,4
arr[[2,3,4]]

array([[23, 96, 57, 47, 97, 52],
       [81, 44, 83, 59, 28, 44],
       [10, 93,  5, 99, 20, 15]])

In [50]:
# fancy indexing row 4,2,3 (in this exact order)
arr[[4,2,3]]

array([[10, 93,  5, 99, 20, 15],
       [23, 96, 57, 47, 97, 52],
       [81, 44, 83, 59, 28, 44]])

### D. NumPy Selection Operation
---

This is in a way similar to indexing, however you can select rows and columns on the basis of conditions. Let's see how you can do it.

In [51]:
arr = np.random.randint(0, 50, (10,))
arr

array([11, 17, 13, 28, 27, 16,  3, 24, 49, 33])

In [52]:
# checks if value at each index is > 15
arr > 15

array([False,  True, False,  True,  True,  True, False,  True,  True,
        True])

In [53]:
# selection on the basis of condition
arr[arr > 15]

array([17, 28, 27, 16, 24, 49, 33])

Now, let us have a look at the arithmetic operations that you can perform using  Numpy.

### E. Arithmetic Operations
---

#### (a). add, subtract, multiply, divide, exponentiation
> * Addition: arr1 + arr2

> * Subtraction: arr1 - arr2

> * Multiplication: arr1 * arr2

> * Division: arr1 / arr2

> * Exponentiation: arr ** n, where n is an number

In [54]:
arr1 = np.arange(10)
print(arr1)
arr2 = np.ones(10)
print(arr2)
arr3 = np.ones(5)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


In [55]:
# addition
print(arr1 + arr2)

# will throw an error as the arrays have to be the same shape
print(arr1 + arr3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [56]:
# subtraction
arr1 - arr2

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [57]:
# multiplication
arr1 * arr1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [58]:
# division
print(arr1 / 2)

# 0's division by 0 will give nan (not a number) value
print(arr1 / arr1)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [59]:
# exponentiation
print(arr1 ** 2)
print(arr1 ** 3.2)

[ 0  1  4  9 16 25 36 49 64 81]
[0.00000000e+00 1.00000000e+00 9.18958684e+00 3.36347354e+01
 8.44485063e+01 1.72466208e+02 3.09089322e+02 5.06190194e+02
 7.76046882e+02 1.13129542e+03]


#### (b). sqrt method

The sqrt method returns square root of each element in the array. The syntax is-
> np.sqrt(arr)

In [60]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

#### (c). exp method

The exp method exponentiates (e<sup>n</sup>) each element in the array. The syntax is-
> np.exp(arr)

In [61]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#### (d). sin method

The sin method returns sine of each element (sin(n)) in the array. The syntax is-
> np.sin(arr)

In [62]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

#### (d). log method

The log method returns logarithm of each element (log(n)) in the array. The syntax is-
> np.log(arr)

In [63]:
np.log(arr1)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

With this, we come to the end of our NumPy tutorial, where we have covered almost all the basic Numpy array methods. In the future tutorials, if we come across a new method, you will be given a tutorial for that. For now, go throught the notebook again before moving on to the quiz. 